# Generated by Django 4.0 on 2022-02-02 19:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('type', models.CharField(help_text='Введіть тип пристрою', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('manufacture', models.CharField(help_text='Введіть назву виробника продукту ', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, help_text="Введіть ім'я", max_length=20)),
                ('last_name', models.CharField(help_text='Введіть фамілію', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Унікальний UUID (створений автоматично)', primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text="Введіть ім'я клієнта", max_length=20)),
                ('last_name', models.CharField(blank=True, help_text='Введіть фамілію клієнта', max_length=20)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='Введіть номер телефону клієнта', max_length=128, region=None, unique=True)),
                ('model', models.CharField(blank=True, help_text='Введіть модель пристрою', max_length=50)),
                ('password', models.CharField(blank=True, default='Без паролю', help_text='Введіть пароль доступу до пристрою', max_length=50)),
                ('serial_number', models.CharField(blank=True, help_text='Введіть серійний номер пристрою', max_length=50)),
                ('reason', models.CharField(help_text='Виберіть тип пристрою', max_length=128)),
                ('is_repairable', models.CharField(blank=True, choices=[('YES', 'Так'), ('NO', 'Ні')], default=False, help_text='Підлягає ремонту', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Введіть ціну на замовлення', max_digits=14)),
                ('open_orded', models.DateTimeField(default=datetime.datetime(2022, 2, 2, 21, 51, 24, 388207), help_text='Введіть дату відкриття замовлення', null=True)),
                ('done_order', models.DateTimeField(blank=True, help_text='Введіть дату закриття замовлення', null=True)),
                ('is_notified', models.CharField(blank=True, choices=[('YES', 'Так'), ('NO', 'Ні')], default=False, help_text='Чи був повідомлений клієнт', max_length=10)),
                ('equipment', models.CharField(blank=True, help_text='Комплектація до пристрою', max_length=200)),
                ('manufacture', models.ForeignKey(help_text='Виробник', null=True, on_delete=django.db.models.deletion.RESTRICT, to='Form.manufacture')),
                ('took_the_orded', models.ForeignKey(help_text='Приймав замовлення', on_delete=django.db.models.deletion.PROTECT, to='Form.master')),
                ('type', models.ForeignKey(help_text='Тип девайсу', on_delete=django.db.models.deletion.PROTECT, to='Form.device')),
            ],
        ),
    ]
