# Generated by Django 4.0 on 2022-01-27 19:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='is_notified',
            field=models.BooleanField(default=False, help_text='Чи був повідомлений клієнт'),
        ),
        migrations.AlterField(
            model_name='form',
            name='done_order',
            field=models.DateTimeField(help_text='Введіть дату закриття замовлення'),
        ),
        migrations.AlterField(
            model_name='form',
            name='is_repairable',
            field=models.CharField(blank=True, choices=[('YES', 'Так'), ('NO', 'Ні')], default=False, help_text='Підлягає ремонту', max_length=10),
        ),
        migrations.AlterField(
            model_name='form',
            name='last_name',
            field=models.CharField(blank=True, help_text='Введіть фамілію клієнта', max_length=20),
        ),
        migrations.AlterField(
            model_name='form',
            name='manufacture',
            field=models.ForeignKey(help_text='Виробник', on_delete=django.db.models.deletion.PROTECT, to='Form.manufacture'),
        ),
        migrations.AlterField(
            model_name='form',
            name='model',
            field=models.CharField(blank=True, help_text='Введіть модель пристрою', max_length=50),
        ),
        migrations.AlterField(
            model_name='form',
            name='open_orded',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 27, 21, 4, 4, 685926), help_text='Введіть дату відкриття замовлення'),
        ),
        migrations.AlterField(
            model_name='form',
            name='password',
            field=models.CharField(blank=True, default='Без паролю', help_text='Введіть пароль доступу до пристрою', max_length=50),
        ),
        migrations.AlterField(
            model_name='form',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Введіть номер телефону клієнта', max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Введіть серійний номер пристрою', max_length=50),
        ),
        migrations.AlterField(
            model_name='form',
            name='took_the_orded',
            field=models.ForeignKey(default='Admin', help_text='Приймав замовлення', on_delete=django.db.models.deletion.SET_DEFAULT, to='Form.master'),
        ),
        migrations.AlterField(
            model_name='form',
            name='type',
            field=models.ForeignKey(help_text='Тип девайсу', on_delete=django.db.models.deletion.PROTECT, to='Form.device'),
        ),
        migrations.AlterField(
            model_name='master',
            name='first_name',
            field=models.CharField(blank=True, help_text="Введіть ім'я", max_length=20),
        ),
    ]
