# Generated by Django 4.0 on 2022-02-02 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0002_alter_device_id_alter_form_id_alter_form_manufacture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='took_the_orded',
            new_name='took_the_order',
        ),
        migrations.RemoveField(
            model_name='form',
            name='open_orded',
        ),
        migrations.AddField(
            model_name='form',
            name='open_order',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 22, 10, 55, 763326), help_text='Введіть дату відкриття замовлення', null=True),
        ),
    ]
