# Generated by Django 4.0 on 2022-01-28 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0002_form_is_notified_alter_form_done_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='price_currency',
        ),
        migrations.AlterField(
            model_name='form',
            name='is_notified',
            field=models.BooleanField(blank=True, choices=[('YES', 'Так'), ('NO', 'Ні')], default=False, help_text='Чи був повідомлений клієнт'),
        ),
        migrations.AlterField(
            model_name='form',
            name='open_orded',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 28, 19, 43, 35, 842793), help_text='Введіть дату відкриття замовлення'),
        ),
        migrations.AlterField(
            model_name='form',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Введіть ціну на замовлення', max_digits=14),
        ),
    ]
