# Generated by Django 4.0 on 2022-02-03 20:46

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0003_rename_took_the_orded_form_took_the_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='open_order',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 3, 22, 46, 20, 73930), help_text='Введіть дату відкриття замовлення', null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Введіть номер телефону клієнта', max_length=128, region=None),
        ),
    ]
