# Generated by Django 4.0 on 2022-01-28 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0004_alter_form_is_notified_alter_form_open_orded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='open_orded',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 28, 20, 46, 48, 388126), help_text='Введіть дату відкриття замовлення'),
        ),
    ]
