# Generated by Django 4.0 on 2022-01-28 18:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0005_alter_form_open_orded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='open_orded',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 28, 20, 53, 26, 193065), help_text='Введіть дату відкриття замовлення'),
        ),
    ]
