# Generated by Django 4.0 on 2022-01-29 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0006_alter_form_open_orded'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='equipment',
            field=models.CharField(blank=True, help_text='Комплектація до пристрою', max_length=200),
        ),
        migrations.AlterField(
            model_name='form',
            name='done_order',
            field=models.DateTimeField(blank=True, help_text='Введіть дату закриття замовлення', null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='open_orded',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 29, 22, 18, 55, 593032), help_text='Введіть дату відкриття замовлення'),
        ),
    ]
