# Generated by Django 4.0 on 2022-01-30 16:56

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0007_form_equipment_alter_form_done_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='form',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Унікальний UUID (створений автоматично)', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='form',
            name='open_orded',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 30, 18, 56, 44, 183795), help_text='Введіть дату відкриття замовлення'),
        ),
        migrations.AlterField(
            model_name='manufacture',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
